name: Unit Tests API

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt

      - name: Copy JSON files
        run: cp api/pending_messages.json api/topics.json api/users.json $GITHUB_WORKSPACE

      - name: Run unit tests
        run: |
          python -m unittest discover -s tests -p '*_test.py'