name: Unit Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api_topics/requirements.txt

      - name: Copy JSON files
        run: cp api_topics/pending_messages.json api_topics/topics.json api_topics/users.json $GITHUB_WORKSPACE

      - name: Run unit tests
        run: |
          python -m unittest discover -s api_topics -p '*_test.py'